server:
   port: 10070
      
spring:
  application:
    name: batch-server
  cloud:
    nacos:
      discovery:
        server-addr: ${nacos.host}:${nacos.port}
        namespace: ${nacos.namespace}
        group: ${spring.profiles.active}
        service: ${spring.application.name}
      config:
        server-addr: ${nacos.host}:${nacos.port}
        namespace: ${nacos.namespace}
        file-extension: yml
        group: ${spring.profiles.active}
  config:
    import:
      - nacos:${spring.application.name}
      - nacos:common
      