server:
   port: 10010

logging:
   config: classpath:logback-custom.xml

spring:
   application:
      name: gateway
   cloud:
      loadbalancer: 
         ribbon: 
            enabled: false
      gateway:
         loadbalancer:
            retry:
                enabled: true
         discovery:
            locator:
                enabled: true
         routes:
            - id: demo-test
              uri: lb://business-server
              predicates: 
              - Path=/demo/**
            - id: feign-test
              uri: lb://business-server
              predicates: 
              - Path=/demo3/**                       
            - id: quartz-test
              uri: lb://scheduler-server
              predicates: 
              - Path=/quartz/**
            - id: auth-test
              uri: lb://auth-server
              predicates: 
              - Path=/oauth/**