server:
   port: 10010

logging:
   config: classpath:logback-custom.xml

spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: ${spring.application.name}
        group: ${spring.profiles.active}
        service: auth-server
      config:
        server-addr: localhost:8848
        namespace: ${spring.application.name}
        file-extension: yml
        group: ${spring.profiles.active}
  config:
    import:
      - nacos:${spring.application.name}
              