server:
  port: 10040

spring:
  datasource:
    driver-class-name: ${scheduler-server.datasource.master.driver-class-name}
    url: ${scheduler-server.datasource.master.url}
    username: ${scheduler-server.datasource.master.username}
    password: ${scheduler-server.datasource.master.password}